# mozna to bude soucasti chartu v budoucnu
# https://github.com/elastic/cloud-on-k8s/pull/7839
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-main-ingress
  # TODO kdybychom nechteli vypinat https
  # to se pak bude hodit na ten elasticsearch hlavne asi
  # annotations:
  # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  # annotations:
  #   traefik.ingress.kubernetes.io/service.scheme: https
spec:
  # todo zmenit pak u nas na nginx
  ingressClassName: traefik
  rules:
    - host: kibana-main.rancher.localhost
      http:
        paths:
          - backend:
              service:
                name: kibana-main-kb-http
                port:
                  number: 5601
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - kibana-main.rancher.local
